plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.myreader'
    compileSdk 34

    defaultConfig {
        applicationId "io.github.myreader"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('myreader.keystore')
            storePassword 'myreader2026'
            keyAlias 'myreader'
            keyPassword 'myreader2026'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}
